// src/components/Links/index.tsx
import React from "react";
import "./index.css";

const Links = () => {
    return (
        <div className="links">
            <a
                href="https://github.com/ArcherGu/easy-qrcode"
                target="_BLANK"
                className="links-button button--large button--secondary button--github"
            >View on GitHub</a>
            <a
                href="/easy-qrcode/docs"
                className="links-button button--large"
            >Documentation</a>
        </div>
    )
}

export default Links;

// deploy/demo/src/components/Links.vue
<template>
    <div class="links">
        <a
            href="https://github.com/ArcherGu/easy-qrcode"
            target="_BLANK"
            class="links-button button--large button--secondary button--github"
        >View on GitHub</a>
        <a
            href="/docs"
            class="links-button button--large"
        >Documentation</a>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'Links',
    components: {},
    props: {},
    setup(props) {},
});
</script>

<style>
</style>
