// src/components/Title/index.tsx
import React from "react";
import logo from "../../assets/logo_2.png";
import "./index.css";

const Title = () => {
    return (
        <div className="title">
            <img
                alt="Easy QRcode"
                src={logo}
                className="logo"
            />
            Easy-QRcode
            <small className="version">0.1.0</small>
        </div>
    )
}

export default Title;

// deploy/demo/src/components/Title.vue
<template>
    <div class="title">
        <img
            alt="Easy QRcode"
            src="../assets/logo_2.png"
            class="logo"
        >
        Easy-QRcode
        <small class="version">({{ version }})</small>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { version } from '../../../../package.json';

export default defineComponent({
    name: 'Title',
    components: {},
    props: {},
    setup(props) {
        return {
            version,
        };
    },
});
</script>

<style>
</style>
